#!/bin/bash
#
# run me to create the LinuxJape, WindowsJape and SolarisJape directories
#
for os in Linux Windows Solaris ; 
  do \
  { mkdir ../${os}Jape ../${os}Jape/build
    cp ${os}/Makefile ../${os}Jape/build ; } ; \
done

