#!/bin/bash
#
# run me to create the LinuxJape, WindowsJape and SolarisJape directories
#
for os in Linux Windows Solaris ; 
  do \
  { mkdir ../${os}Jape ../${os}Jape/build
    ln -s ../../CommonBuildResources/${os}/Makefile ../${os}Jape/build/Makefile
    ln -s ../../examples ../${os}Jape/build/examples ; } ; \
done

