#!/bin/bash
# usage: source opencvs; sourcedistrib <tag>
function retrieve {
if cmp $1/$2 $2 >/dev/null; then rm -f $1/$2; else mv -f $1/$2 new$2; fi
}
rm -fr jape.source jape.source.$1.tgz
cvs export -r $1 -d jape.source distrib
(cd jape.source/CommonBuildResources; bash create_OS_directories; rm -fr create_OS_directories Linux Windows Solaris)
retrieve jape.source/CommonBuildResources sourcedistrib
retrieve jape.source/CommonBuildResources opencvs
(cd jape.source/CommonBuildResources/InstallerKit; ant buildinstaller; mv BUILD/buildinstaller.jar ..; ant clean)
retrieve jape.source/MacOSX macdistrib
tar cvzf jape.source.$1.tgz jape.source
