/* $Id$ */

/* forcing semantics */

SEMANTICTURNSTILE IS í

FORCE A¦B IFF FORCE A AND FORCE B
FORCE AëB IFF FORCE A OR FORCE B
FORCE AçB IFF ALL (FORCE A IMPLIES FORCE B)
FORCE ÂA IFF NONE FORCE A

FORCE èx.P(x) IFF ALL (FORCE actual i IMPLIES FORCE P(i))
FORCE äx.P(x) IFF FORCE actual i AND FORCE P(i)

