/* $Id$ */

/* forcing semantics */

SEMANTICTURNSTILE æ IS í

FORCEDEF A¦B IS BOTH (FORCE A) (FORCE B)
FORCEDEF AëB IS EITHER (FORCE A) (FORCE B)
FORCEDEF AçB IS EVERYWHERE (IF (FORCE A) (FORCE B))
FORCEDEF ÂA IS NOWHERE (FORCE A)

FORCEDEF èx.P(x) IS EVERYWHERE (ALL (actual i) (FORCE (P(i))))
FORCEDEF äx.P(x) IS SOME (actual i) ( FORCE (P(i)))

