/* $Id$ */

/* forcing semantics */

SEMANTICTURNSTILE IS í

FORCE A¦B IFF FORCE A AND FORCE B
FORCE AëB IFF FORCE A OR FORCE B
FORCE AçB IFF EVERYWHERE (FORCE A IMPLIES FORCE B)
FORCE ÂA IFF NOWHERE FORCE A

FORCE èx.P(x) IFF EVERYWHERE ALL actual i  FORCE P(i)
FORCE äx.P(x) IFF SOME actual i  FORCE P(i)

