#!/bin/sh
#
# Fetch distributions and install them
#
#
architectures="Solaris Windows Linux MacOsX"
build=/home/sufrin/JAPETREE-6/jape
README=/home/sufrin/JAPETREE-6/jape/CommonBuildResources/
#
#
#
distdir=BUILDS/`date +%Y%m%d`
message=$distdir/README
#
#
#
echo -n Distribution Directory $distdir
if [ -d $distdir ]
then
 echo " exists."
else
 mkdir $distdir
 echo  " created."
fi
for arch in $architectures
do
  source=$build/${arch}Jape/build/${arch}jape.jar
  if [ -e $source ]
  then 
     if [ -e $distdir/${arch}jape.jar ]
     then
       echo $arch already installed.
     else
       cp   $source $distdir
       echo $arch installed.
     fi
  else
     echo -e $arch not installed.
  fi 
done
  rm -f CURRENT
  ln -s $distdir        CURRENT
  cp -p $README/README* $distdir
  echo Current distribution made on `date`      >  $message
  echo                                          >> $message
  cat MESSAGE                                   >> $message


