name: jape # registered
base: core20 # jape_engine was compiled under 20.04, so we need core 20
version: '9.1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: a configurable proof calculator # 79 char long summary
description: |
  Jape is a configurable proof calculator which supports the interactive discovery 
  of formal proofs in inference systems.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

layout:
  /proc/1/cgroup:
    bind: $SNAP_DATA/proc/1/cgroup
    
plugs:
  java-prefs:
    interface: personal-files
    read:
    - $HOME/.java
    write:
    - $HOME/.java

parts:
  jape:
    plugin: dump
    source: Jape.app
    build-attributes: [keep-execstack]

apps:
  jape:
    command: launchstub
    extensions: [gnome-3-38]
    plugs: 
    - java-prefs
    - home
    
