#!/bin/bash
# usage: macdistrib <tag>
# Run from MacOSX 
# builds jape_<tag> distribution, which you have to pack up using DiskUtility (sorry)

make release

(cd ../utf8_encoder; make)

rm -fr jape_$1 jape_$1.dmg
mkdir jape_$1 jape_$1/utf8_encoder

# rsync -l because Jape.app includes a symbolic link (recommended by jarbundler.jar docs)

rsync -rlvt build/Jape.app jape_$1
rsync -rvt  ../examples README.html jape_$1
rsync -rvt  ../utf8_encoder/{encoder.jar,README_encoder.txt} jape_$1/utf8_encoder
rsync -rvt  ..//CommonBuildResources/License.txt jape_$1

sh makedmg jape_$1







