#
# $Id$
#
#
# 
#
components::  ; (cd ../../CommonBuildResources/; make -f Makefile-java installjape.jar)
#
#
#
include ../../CommonBuildResources/Makefile-common
#
#
#
OS=Windows
#
# Override the special targets
#
ENGINETARGET=makejape.bat
BUILTENGINE=jape.exe
DEPLOYEDENGINE=jape.exe
README=README-WINDOWS 
INSTALLME=installjape.jar
DEPLOYMENTKIT=$(README) installjape.jar
                


